application: abhishek-blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:                                                                      
- name: jinja2                                                                  
  version: latest                                                               
- name: markupsafe                                                              
  version: latest                                                                                

handlers:
 
- url: /style
  static_dir: templates/style

- url: /img
  static_dir: templates/img 
- url: /.*
  script: blog.app

- url: /blog/(\d+)
  script: blog.app
  